[package]
name = "nl80211scan"
version = "0.1.0"
edition = "2021"

[dependencies]
neli = { version = "0.6", features = ["async"] }
num_enum = "*"
macaddr = "*"
anyhow = "*"
tokio = { version = "1", features = ["full"] }
