[package]
name = "nl80211scan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
neli = { version = "0.6", features = ["async"] }
macaddr = "1"
